django_app_lti/urls.py
from django.conf.urls import url
from .views import LTILaunchView, LTIToolConfigView, logout_view, logged_out_view

urlpatterns = [
    url(r'^$', LTILaunchView.as_view(), name='index'),
    url(r'^launch$', LTILaunchView.as_view(), name='launch'),
    url(r'^config$', LTIToolConfigView.as_view(), name='config'),
    url(r'^logout$', logout_view, name="logout"),
    url(r'^logged-out$', logged_out_view, name="logged-out"),
]

foundcat/urls.py
# -*- coding: utf-8 -*-
#
# Copyright © FoundCAT <team.foundcat@fh-aachen.de>
#
# This file is part of FoundCAT <https://cat.fh-aachen.de/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""foundcat URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin

import foundcat.views.dashboard as dashboard
import foundcat.views.repo as repo
import foundcat.views.edit as edit
import foundcat.views.dictionary as dictionary
import foundcat.views.files as files
import foundcat.views.lang as lang

import weblate.trans.views.js
import weblate.trans.views.lock
import weblate.trans.views.edit
import django.views.i18n

import foundcat.accounts_urls
#import weblate.trans.views.basic
import foundcat.views.basic
import weblate.trans.views.widgets

import django_app_lti.urls

from foundcat.admin import SITE as admin

# URL regexp for language code
LANGUAGE = r'(?P<lang>[^/]+)'

# URL regexp for language code
TARGETLANGUAGE = r'(?P<targetlang>[^/]+)'



# URL regexp for project
PROJECT = r'(?P<project>[^/]+)/'

# URL regexp for subproject
SUBPROJECT = PROJECT + r'(?P<subproject>[^/]+)/'

# URL regexp for translations
TRANSLATION = SUBPROJECT + LANGUAGE + '/'


# URL regexp used as base for widgets
WIDGET = r'(?P<widget>[^/-]+)-(?P<color>[^/-]+)'
# Widget extension match
EXTENSION = r'(?P<extension>(png|svg|bin))'

urlpatterns = [

    url(r'^wl/', include('foundcat.wl_urls')),
    
    url(
        r'^$', 
        dashboard.home, 
        name='home'
    ),

    url(
      r'^pair/' + LANGUAGE + '/' + TARGETLANGUAGE + '$',
      lang.pairs,
      name='pairs'
    ),
    url(
      r'^pair_choose$',
      lang.choose_langpair,
      name='choose_langpair'
    ),

    url(
      r'^foundcat-add-lang/' + SUBPROJECT + '$',
      foundcat.views.basic.new_language,
      name="foundcat-add-lang"
    ),

    url(
        r'^download/translation/' + TRANSLATION + '$',
        files.download_translation,
        name='download_translation_doc',
    ),

    

    # Duolayout
    url(
        r'^translate/' + TRANSLATION + '$',
        edit.translate,
        name='translate',
    ),
    

    # Comments
    url(
        r'^comment-fc/(?P<pk>[0-9]+)/$',
        edit.comment,
        name='comment-fc',
    ),

    # GET (overview)
    url(
        r'^projects/' + PROJECT + 'add/$',
        repo.add,
        name='repo_add',
    ),
    # POST
    url(
        r'^projects/' + PROJECT + 'add_wiki/$',
        repo.add_wiki,
        name='repo_add_wiki',
    ),

    # GET wiki_query=
    url(
        r'^projects/' + PROJECT + 'upload_wiki/$',
        repo.upload_wiki,
        name='repo_upload_wiki',
    ),
    url(
        r'^projects/' + PROJECT + 'edit/' + r'(?P<subproject>[^/]+)/',
        repo.edit,
        name='repo_edit',
    ),
    # POST
    url(
        r'^projects/' + PROJECT + 'upload_text',
        repo.upload,
        name='repo_upload',
    ),
    #Translation pages
    url(
        r'^download/source/' + SUBPROJECT + '$', # By Sebi
        files.download_source,
        name='download_source',
    ),

    
    url(
        r'^js/foundcat-glossary/(?P<unit_id>[0-9]+)/$',
        dictionary.add_dictionary, # By Sebi
        name='foundcat-js-add-glossary',
    ),
    
    url(
        r'^js/foundcat-set-error-category/(?P<change_id>[0-9]+)/$',
        edit.set_error_category, # By Sebi
        name='js-set-error-category',
    ),

    url(r'^admin/', include(admin.urls)),


    url(r'^accounts/', include('foundcat.accounts_urls')),
    

    # Include the lti app's urls
    url(r'^lti/', include(django_app_lti.urls, namespace="lti")),
    url(r'^lti/success/(?P<resource_id>[0-9]+)/', dashboard.foundcat_lti, name='foundcat_lti',)
    
    #url(r'^', include('weblate.urls')),

]

foundcat/models.py
# -*- coding: utf-8 -*-
#
# Copyright © FoundCAT <team.foundcat@fh-aachen.de>
#
# This file is part of FoundCAT <https://cat.fh-aachen.de/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from django.contrib.auth.models import User
from weblate.trans.models.subproject import SubProject
from weblate.trans.models.project import Project
from weblate.trans.models.translation import Translation
from weblate.trans.models.change import Change
from django.conf import settings
from django.utils.text import slugify
from translate.convert.txt2po import txt2po

from git import Repo
from translate.storage.po import pofile
from translate.storage.txt import TxtFile
from django.utils.encoding import python_2_unicode_compatible

import os

@python_2_unicode_compatible
class TextRepo(models.Model):
    FLAVOURS = (
        ('P', 'Plaintext'),
        ('W', 'Wikitext'),
        ('F', 'FoundCAT Wikitext'),
    )

    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=100,unique=True)
    text = models.TextField(verbose_name='Segments')
    owner =  models.ForeignKey(User)
    repo =  models.ForeignKey(SubProject, null=True)
    flavour = models.CharField(max_length=2, choices=FLAVOURS, default='F')
    project = models.ForeignKey(Project)
    pub_date = models.DateTimeField('date published', null=True),
    create_date = models.DateTimeField('date created')

    source = models.TextField(verbose_name='Source text', null=True)

    def __str__(self):
        return self.title

    def git_dir(self):
	data_dir = settings.DATA_DIR.replace('/weblate/../data', '/data')
        translations_dir = os.path.join(data_dir, 'translations')
        user_dir = os.path.join(translations_dir, slugify(self.owner.id))
        return os.path.join(user_dir, "%s.git" % slugify(self.title))
    
    def locale_dir(self):
        return os.path.join(self.git_dir(), 'locale')
    
    def create_dir(self):
        git_dir = self.git_dir()
        locale_dir = self.locale_dir()
        if not os.path.exists(git_dir):
            os.makedirs(git_dir)
            Repo.init(git_dir)
            if not os.path.exists(locale_dir):
                os.makedirs(locale_dir)
                

    def source_txt(self):
        return os.path.join(self.git_dir(), 'source.txt')

    def po_template(self):
        return os.path.join(self.locale_dir(), self.project.source_language.code + '.pot')
            
    def write_source(self):
        text = u"{}\n\n{}".format(self.title, self.text)
    
        text_file = open(self.source_txt(), "w")
        text_file.write(text.encode('utf8'))
        text_file.close()
        
    def choose_input_store(self, inputfile):
        return TxtFile(inputfile, encoding="utf-8")
        
    def convert(self):
        inputfile  = open(self.source_txt(), "r")
        outputfile = open(self.po_template(), "w+")
        
        convertor = txt2po(duplicatestyle="msgctext")
        outputstore = convertor.convertstore(self.choose_input_store(inputfile))
        if outputstore.isempty():
            return 0
            
        outputstore.serialize(outputfile)

        outputfile.close()
        inputfile.close()
         

    def commit_changes(self):
        repo = Repo(self.git_dir())

        index = repo.index
        
        index.add('*')
        
        index.commit('Translation Repo created by foundcat script')
        
        
    def get_units(self):
        inputfile = open(self.po_template(), "r")
        inputstore = pofile(inputfile, encoding="utf-8")
        inputfile.close()
        return inputstore.units[1:]

    def save(self, *args, **kwargs):
        changed_source = False
        if getattr(self, '_title_changed', True):
            self.slug = slugify(self.title)
        if changed_source or getattr(self, '_text_changed', True):
            self.create_dir()
            self.write_source()
            self.convert()
            self.commit_changes()
        super(TextRepo, self).save(*args, **kwargs)

    @property
    def is_published(self):
        return self.repo is not None
        
    def get_translations(self):
        if self.is_published:
            return Translation.objects.filter(
                subproject = self.repo
            )
        
        
        
        
        
        
        
        
        
        
        

class ImprovementCategory(models.Model):
    title = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True, null=True)
    pos = models.IntegerField(null=True)

    def __str__(self):
        return self.title



class ChangeImprovement(models.Model):
    improvement_category = models.ForeignKey(ImprovementCategory)
    change = models.ForeignKey(Change)


class ProfileExtension(models.Model):
    user = models.ForeignKey(User)
    subscribed_edited_units = models.BooleanField(default=True, verbose_name='Receive email notifications for changes on edited segments',)

foundcat/views/accounts.py
# -*- coding: utf-8 -*-
#
# Copyright © FoundCAT <team.foundcat@fh-aachen.de>
#
# This file is part of FoundCAT <https://cat.fh-aachen.de/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from foundcat.forms import SettingsForm
from foundcat.models import ProfileExtension
from weblate.trans.util import render
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from weblate.utils import messages

@never_cache
@login_required
def settings(request):
  user = request.user
  pe = ProfileExtension.objects.filter(user=user)
  if pe.count() == 0:
    pe = ProfileExtension.objects.create(user=user)
    pe.save()
  else:
    pe = pe[0]

  form = SettingsForm(instance=pe)
  if request.method == "POST":
    form = SettingsForm(request.POST, instance=pe)
    if form.is_valid():
      form.save()
      messages.success(request, 'Settings have been saved.')
      return HttpResponseRedirect(reverse('profile'))


  return render(
      request,
      'accounts/settings.html',
      {
         'form': form
      }
  )

foundcat/views/basic.py
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count, F
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils import translation
from django.views.decorators.cache import never_cache
from django.utils.encoding import force_text
from django.utils.html import escape
from django.utils.http import urlencode
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.translation.trans_real import parse_accept_lang_header
import django.views.defaults

from weblate.utils import messages
from weblate.trans.models import (
    Project, Translation, Check, ComponentList, Change, Unit, IndexUpdate,
)
from weblate.requirements import get_versions, get_optional_versions
from weblate.lang.models import Language
from weblate.trans.forms import (
    get_upload_form, SearchForm, SiteSearchForm,
    AutoForm, ReviewForm, get_new_language_form,
    ReportsForm, ReplaceForm, 
)
from weblate.permissions.helpers import (
    can_automatic_translation, can_translate,
)
from weblate.accounts.models import Profile
from weblate.accounts.notifications import notify_new_language
from weblate.trans.stats import get_per_language_stats
from weblate.trans.views.helper import (
    get_project, get_subproject, get_translation,
    try_set_language,
)
from weblate.trans.util import (
    render, sort_objects, sort_unicode, translation_percent,
)
import weblate


@never_cache
@login_required
def new_language(request, project, subproject):
    obj = get_subproject(request, project, subproject)

    form_class = get_new_language_form(request, obj)

    if request.method == 'POST':
        form = form_class(obj, request.POST)
#        form.helper.form_action = 'test'

        last_lang = 'en_GB'

        if form.is_valid():
            langs = form.cleaned_data['lang']
            for language in Language.objects.filter(code__in=langs):
                last_lang=language
                if obj.new_lang == 'contact':
                    notify_new_language(obj, language, request.user)
                    messages.success(
                        request,
                        _(
                            "A request for a new translation has been "
                            "sent to the project's maintainers."
                        )
                    )
                elif obj.new_lang == 'add':
                    obj.add_new_language(language, request)
            return redirect(reverse('translate', kwargs={'project':obj.project.slug, 'subproject':obj.slug, 'lang':last_lang.code}))
        else:
            messages.error(
                request,
                _('Please fix errors in the form.')
            )
    else:
        form = form_class(obj)

    return render(
        request,
        'foundcat-add-lang.html',
        {
            'object': obj,
            'project': obj.project,
            'form': form,
        }
    )

foundcat/templates/add.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load permissions %}
{% load translations %}
{% load foundcat_extras %}

{% block extra_meta %}
  <script src="{% static 'foundcat-textrepo.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'textrepo.edit.css' %}">
{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}">{{ object }}</a></li>
<li>My source texts</li>
{% endblock %}

{% block content %}

<ul class="nav nav-tabs" role="tablist">

    <li role="presentation" class="active">
        <a href="{% url 'repo_add' object.slug %}#wikisource" aria-controls="wikisource" role="tab" data-toggle="tab">
            Upload Wikipedia page
        </a>
    </li>
    <li role="presentation">
        <a href="{% url 'repo_add' object.slug %}#sourcetext" aria-controls="sourcetext" role="tab" data-toggle="tab">
            Upload text
        </a>
    </li>
    <li role="presentation">
        <a href="{% url 'repo_add' object.slug %}#mytexts" aria-controls="mytexts" role="tab" data-toggle="tab">
            My source texts
        </a>
    </li>
</ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="wikisource">
        <div class="content">
            <form action="{% url 'repo_add_wiki' object.slug %}#sourcetext">
                <div class="input-group">
                    <input type="text" name="wiki_query" class="form-control" placeholder="e.g.  https://de.wikipedia.org/wiki/Kraftwerk_Weisweiler  or  Kraftwerk Weisweiler" />
                    
                    <span class="input-group-btn">
                        <input type="submit" value="Search" class="btn btn-default" />
                    </span>
                </div>
            </form>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="sourcetext">
        <div class="content">
            <form action="{% url 'repo_upload' object.slug %}#sourcetext" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Preview</button>
            </form>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="mytexts">
        <div class="content">
            <ul class="list-group">
                {% for repo in myrepos %}
                    <li class="list-group-item {% if repo.is_published %}list-group-item-success{% else %}list-group-item-danger{% endif %}">
                        {% if repo.is_published %}
                            {% translation_progress repo.repo %}
                        {% endif %}
                        <div class="repo-created-date pull-right">
                            Uploaded {{ repo.create_date|naturaltime }}
                        </div>
                        {% if repo.is_published %}
                            <a href="{% url 'translate' object.slug repo.slug 'en_GB' %}">
                                <strong>{{ repo.title }}</strong> (published)
                            </a>
                            {% if user.is_staff %}
                                <a href="{% url 'repo_edit' object.slug repo.slug %}" class="btn btn-default">Show</a>
                            {% endif %}
                            

                        {% else %}
                            
                            <strong>{{ repo.title }}</strong> (not published)
                            
                            <div>
                                <a href="{% url 'repo_edit' object.slug repo.slug %}" class="btn btn-default">Edit</a>
                                <form style="display:inline" action="{% url 'repo_edit' object.slug repo.slug %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" name="delete" type="submit">Delete</button>
                                </form>
                            </div>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>


<div class="source-language">
Source language: <span>{{ object.source_language }}</span>
</div>


{% endblock %}

foundcat/templates/dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load translations %}
{% load permissions %}
{% load crispy_forms_tags %}
{% load foundcat_extras %}

{% load static %}


{% block extra_meta %}

<link rel="stylesheet" type="text/css" href="{% static 'foundcat.css' %}" />
<script src="{% static 'dashboard.js' %}"></script>

{% endblock %}  

{% block breadcrumbs %}
<li>Dashboard ({{ object.name }})</li>


<img src="{% url 'widget-image' project=object.slug widget='svg' color='badge' extension='svg' %}" class="pull-right flip" />
{% endblock %}

{% block content %}

{% whiteboard_messages project=object %}

{% can_see_repository_status user object as user_can_see_repository_status %}
{% can_commit_translation user object as user_can_commit_translation %}
{% can_manage_acl user object as user_can_manage_acl %}
{% can_edit_project user object as user_can_edit_project %}


<div class="tab-pane active" id="components">

<a href="{{ add_url }}" class="btn btn-default pull-left">Add source text</a>

{% include "legend.html" %}

<table class="sort table">
<thead>
<tr>
<th>Title</th>
<th style="text-align: right">Recent activity</th>
<th colspan="2">{% trans "Translated" %}</th>
<!--<th colspan="2">{% trans "Words" %}</th>
<th>Translate</th>-->
</tr>
<tbody>
{% for prj in object.subproject_set.select_related %}
<tr>
<th>



{% foundcat_duo_link prj %}


</th>
<td class="activity">
    {% recent_project_change prj %}
</td>
<td class="progress-cell">
    {% translation_progress prj %}
</td>
<td class="percent" style="width: 6%">
    {{ prj.get_translated_percent }}%
</td>
</tr>
{% endfor %}
</tbody>
</table>

</div>



{% endblock %}

foundcat/templates/duo-link.html
{% if url %}
    <a href="{{ url }}">
        {{ title }}
    </a>
{% endif %}

foundcat/templates/footer.html
{% load translations %}
{% load i18n %}
<footer class="flip pull-left">
 <ul>
  <li>{% blocktrans %}Powered by FoundCAT, based on Weblate {{ version }}{% endblocktrans %}</li>
  <li><a href="{% url 'about' %}">{% blocktrans %}About Weblate{% endblocktrans %}</a></li>
  {% if legal %}<li><a href="{% url 'legal:index' %}">{% trans "Legal" %}</a></li>{% endif %}
  {% if status_url %}<li><a href="{{ status_url }}">{% trans "Service status" %}</a></li>{% endif %}
  <li><a href="{% url 'contact' %}">{% trans "Contact us" %}</a></li>
  <li><a href="https://bluecloud.academy/mod/forum/view.php?id=5>Help</a></li>
  <li><a href="{{ donate_url }}">{% trans "Donate to Weblate!" %}</a></li>
 </ul>
</footer>

{% if piwik_site_id and piwik_url %}
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['setCustomVariable', 1, 'Language', '{{ LANGUAGE_CODE }}', 'page']);
  {% if project %}
  _paq.push(['setCustomVariable', 2, 'Project', '{{ project.name }}', 'page']);
  {% endif %}
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//{{ piwik_url }}/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', {{ piwik_site_id }}]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//{{ piwik_url }}/piwik.php?idsite={{ piwik_site_id }}" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
{% endif %}

{% if google_analytics_id %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ google_analytics_id }}', 'auto');
  ga('send', 'pageview', {
  {% if project %}
    'dimension2':  '{{ project.name }}',
  {% endif %}
    'dimension1':  '{{ LANGUAGE_CODE }}'
  });

</script>
{% endif %}

foundcat/templates/foundcat-add-lang.html
{% extends "base.html" %}
{% load i18n %}
{% load permissions %}
{% load translations %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li><a href="{{ object.project.get_absolute_url }}">{{ object.project }}</a></li>
<li><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></li>
{% endblock %}

{% block content %}
{% can_add_translation user object.project as user_can_add_translation %}

{% if object.can_add_language and user_can_add_translation %}

<div class="tab-pane" id="newlang">

<form action="{% url 'foundcat-add-lang' project=object.project.slug subproject=object.slug %}" method="post">
{% csrf_token %}
<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Start new translation" %}</h4></div>
  <div class="panel-body">
{% if object.new_lang == 'url' %}
<p>{% blocktrans with object.project.instructions as url %}Should your language be missing, please follow <a href="{{ url }}">the translator instructions</a>.{% endblocktrans %}</p>
{% else %}
<p>{% trans "Please choose the language you want to translate to." %}</p>
{% if object.new_lang == 'contact' %}
<p>{% trans "Project maintainers are notified of this request, which prompts them to add the language manually." %}</p>
{% endif %}
{{ form|crispy }}
<p class="help-block"><a href="{% url 'contact' %}?t=lang">{% trans "Can't find your language in the list above?" %}</a></p>
</div>
<div class="panel-footer">
{% if object.new_lang == 'contact' %}
<input class="btn btn-default" type="submit" value="{% trans "Request new translation" %}" />
{% else %}
<input class="btn btn-default" type="submit" value="{% trans "Start new translation" %}" />
{% endif %}
{% endif %}
</div>
</div>
</form>

</div>
{% endif %}

{% endblock %}

foundcat/templates/foundcat-list-changes.html
{% load i18n %}
{% load translations %}
{% load permissions %}
{% load crispy_forms_tags %}
{% load foundcat_extras %}

<ul class="list-unstyled">

    {% for c in change_list %}
        <li class="clearfix">
            {% if c.form %}
                
                <form class="set-error-category" action="{% url 'js-set-error-category' change_id=c.change.id %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group">
                      <div class="input-group-addon">
                        <i id="errorcategory-add-loading" class="fa fa-spinner fa-spin" style="display: none;"></i>
                        Improvement
                      </div>
                      {{ c.form }}
                    </div>
                </form>

            {% endif %}

            <span class="change-text">
                {% if c.change.action == c.change.ACTION_SUGGESTION %}
                    {% format_translation c.change.target unit.translation.language diff=unit.target simple=True %}
                {% elif c.old %}
                    {% format_translation c.change.target unit.translation.language diff=c.old simple=True %}
                {% else %}
                    {% format_translation c.change.target unit.translation.language simple=True %}
                {% endif %}
            </span>

            <div class="user-info">
            {{ c.change.get_user_display }}
            {% if c.change.user %}{% show_badges c.change.user %}{% endif %}
            {{ c.change.timestamp|naturaltime }}

            <span>
                {% if c.improvement %}
                    Improvement: {{ c.improvement.improvement_category }}
                {% else %}
                    {{ c.change.get_action_display }}
                {% endif %}
            </span>

            </div>
            
        </li>
    {% empty %}
        <li>           
            <span title="">Be the first to translate this segment</span>
        </li>
    {% endfor %}
</ul>
<button class="btn btn-default btn-xs more-changes">Show more changes</button>

foundcat/templates/foundcat-source-glossary.html
{% load foundcat_extras %}

<div class="txt">
    {% show_source_text_glossary item.source glossary %}
</div>

foundcat/templates/recent-user.html
{% load translations %}
{% load foundcat_extras %}

{% if change %}{% with change as c %}
    {% with c.get_action_display as action and c.unit.get_absolute_url|duo as url %}
        <span style="display:none">{{ c.timestamp|date:"U" }}</span>

        {% if c.user %}
            <div class="activity-1">
                {{ c.user.profile.get_user_display_link }}
                {{ c.timestamp|naturaltime }}<!--
            --></div>
            <div class="activity-2">
                {% if c.unit %}
                    <a href="{{ url }}">{{ action }}</a>
                {% else %}
                    {{ action }}
                {% endif %}
            </div>
        {% else %}
            <div class="activity-1 activity-single">
                Published {{ c.timestamp|naturaltime }}
            </div>
        {% endif %}
    {% endwith %}
{% endwith %}{% endif %}

foundcat/templates/source_text_glossary.html
{{ glossary_html|safe }}